CREATE TABLE IF NOT EXISTS customers(
    id INTEGER NOT NULL PRIMARY KEY,
    FIO VARCHAR(50) NOT NULL,
    number_phone VARCHAR(13)
);
CREATE TABLE IF NOT EXISTS managers(
    id INTEGER NOT NULL PRIMARY KEY,
    FIO VARCHAR(50) NOT NULL,
    number_phone VARCHAR(13) NOT NULL,
    passport INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS applications(
    id INTEGER NOT NULL PRIMARY KEY,
    application_date DATE NOT NULL,
    desired_travel VARCHAR(30) NOT NULL,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    manager_id INTEGER NOT NULL REFERENCES managers(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    status BOOLEAN DEFAULT false
);
CREATE TABLE IF NOT EXISTS implementers(
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    description VARCHAR(60) NOT NULL,
    contact_detail VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS contracts(
    id INTEGER NOT NULL PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    implementer_id INTEGER NOT NULL REFERENCES implementer(id) ON DELETE CASCADE ON UPDATE NO ACTION,
    comment_imp VARCHAR(80)
);
CREATE TABLE IF NOT EXISTS posts(
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    authority VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS users(
    id INTEGER NOT NULL PRIMARY KEY,
    login VARCHAR(15) NOT NULL,
    password VARCHAR(20) NOT NULL
);